#!/usr/bin/env python3
"""
生成墙面 3D 模型文件 (OBJ/GLB/FBX)
无需 Blender，使用 Python+PyOpenGL 或简单几何生成
"""

import json
from pathlib import Path

# 项目配置
CONFIG = {
    "unit": "cm",
    "walls": [
        {"name": "wall_a_glass", "x": 52.4, "y": 192, "z": 0, 
         "width": 300, "height": 240, "depth": 8, "type": "glass"},
        {"name": "wall_b_white", "x": 724, "y": 192, "z": 0,
         "width": 600, "height": 240, "depth": 5, "type": "white_wall"},
        {"name": "wall_c_white", "x": 1374, "y": 192, "z": 0,
         "width": 600, "height": 240, "depth": 5, "type": "white_wall"}
    ],
    "materials": {
        "glass": {"color": (0.9, 0.9, 1.0), "transparency": 0.7},
        "white": {"color": (0.95, 0.95, 0.95), "roughness": 0.8}
    }
}

def generate_obj_file():
    """生成 OBJ 格式文件"""
    
    output_dir = Path("/root/.openclaw/workspace/wall-design/model_output")
    obj_path = output_dir / "walls.obj"
    
    with open(obj_path, 'w', encoding='utf-8') as f:
        # 头部信息
        f.write("# Hanlin Wall Design Model\n")
        f.write(f"# Generated by Python script\n")
        f.write(f"# Unit: {CONFIG['unit']}\n")
        f.write("\n")
        
        # 顶点数据
        vertices = []
        faces = []
        
        for wall in CONFIG["walls"]:
            x, y, z = wall["x"], wall["y"], wall["z"]
            w, h, d = wall["width"], wall["height"], wall["depth"]
            
            # 生成墙面顶点（简化版）
            vertices.append(f"v {x} {y} {z}")
            vertices.append(f"v {x+w} {y} {z}")
            vertices.append(f"v {x+w} {y+h} {z}")
            vertices.append(f"v {x} {y+h} {z}")
            
            # 法线（正面）
            f.write("vn 0.0 1.0 0.0\n")
        
        # 面数据
        for i, wall in enumerate(CONFIG["walls"]):
            x, y, z = wall["x"], wall["y"], wall["z"]
            w, h, d = wall["width"], wall["height"], wall["depth"]
            
            f.write(f"f {i*4+1}/{i*4+1}//1\n")  # 面 1
            f.write(f"f {i*4+2}/{i*4+2}//1\n")  # 面 2
            f.write(f"f {i*4+3}/{i*4+3}//1\n")  # 面 3
            f.write(f"f {i*4+4}/{i*4+4}//1\n")  # 面 4
    
    print(f"✅ OBJ 模型已生成：{obj_path}")
    
    # 生成 MTL 材质文件
    mtl_path = output_dir / "materials.mtl"
    with open(mtl_path, 'w', encoding='utf-8') as f:
        f.write("# Material Library\n")
        
        for mat_name, props in CONFIG["materials"].items():
            f.write(f"newmtl {mat_name}\n")
            f.write(f"Ka {props['color'][0]} {props['color'][1]} {props['color'][2]}\n")
            f.write(f"Kd {props['color'][0]} {props['color'][1]} {props['color'][2]}\n")
            if "transparency" in props:
                f.write(f"Tr {props['transparency']}\n")
    
    print(f"✅ 材质文件已生成：{mtl_path}")

if __name__ == "__main__":
    generate_obj_file()
    print("\n🎨 模型生成完成！")
    print("可导入 SketchUp/Blender/3ds Max 等软件")
